apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service-deployment
  labels:
    app: hotel-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: hotels:pod
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          ports:
            - containerPort: 8081