server:
  port: 8081

spring:
  application:
    name: Hotel-Service
  datasource:
    #url: jdbc:postgresql://localhost:5432/HotelDB
    url: jdbc:postgresql://pg-2bf38ab2-shardathakur223-9962.a.aivencloud.com:16868/defaultdb?sslmode=require
    #username: postgres
    #password: postgres
    password: AVNS_NLg4FfaA0r4ya9Uuzew
    username: avnadmin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.126.68.85:8761/eureka

