apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service-deployment
  labels:
    app: rating-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: ratings:pod
          resources:
            limits:
              memory: "500Mi"
              cpu: "150m"
          ports:
            - containerPort: 8082