apiVersion: v1
kind: Pod
metadata:
  name: userservice-pod
  labels:
    name: userservice
spec:
  containers:
    - name: userservice-container
      image: users:pod
      imagePullPolicy: Never
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"